// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Domain.Models.Shared;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class Season
{
    [Key]
    public int SeasonsId { get; set; }

    public int Type { get; set; }

    public SeasonType SeasonType { get; set; }

    [Required]
    public string PossibleWeathers { get; set; }


    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public ICollection<SeasonWeatherAllowed> AllowedWeathers { get; set; }


}