// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public abstract class TrophyBase
{
    [Key]
    public int TrophyId { get; set; }
    public string TrophyName { get; set; }
    public string Description { get; set; }
    public DateTime DateAwarded { get; set; }
}