// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class HorseArtist
{
    [Key]
    public int HorseArtistId { get; set; }

    public Guid UserId { get; set; }

    public int SubmissionsAwaiting { get; set; }

    public int SubmissionAccepted { get; set; }


    [ForeignKey("UserId")]
    public virtual User User { get; set; }
}