// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Users;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class Role
{
    [Key]
    public int RoleId { get; set; }

    [Required]
    public string Name { get; set; }

    public virtual ICollection<User> Users { get; set; }

    [ForeignKey("RoleId")]

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}