// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Users;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class User
{
    [Key]
    public Guid UserId { get; set; }

    [Required]
    public string UserName { get; set; }

    [Required]
    public string UserEmail { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    public string Name { get; set; }


    public string Age { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime LastLogin { get; set; }


    public bool IsSystemUser { get; set; }

    public virtual ICollection<PlayerTrophy> PlayerTrophies { get; set; } = new List<PlayerTrophy>();

    [ForeignKey("UserId")]

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

}