// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

    public class CompetitionEntry
    {
        [Key]
        public int EntryId { get; set; }

        public int CompetitionId { get; set; }

        public Guid GuidHorseId { get; set; }

        public DateTime EntryTime { get; set; }

        [ForeignKey("CompetitionId")]

        public virtual Competition Competition { get; set; }

        [ForeignKey("GuidHorseId")]
        public virtual Horse Horse { get; set; }
    }