// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

    public class CompetitionResult
    {
        [Key]
        public int ResultId { get; set; }

        public int CompetitionId { get; set; }

        public Guid GuidHorseId { get; set; }

        public int Placement { get; set; }

        public PointType PointType { get; set; }

        public int PointsEarned { get; set; }

        public int PlacementPrice { get; set; }

        [ForeignKey("CompetitionId")]

        public virtual Competition Competition { get; set; }

        [ForeignKey("GuidHorseId")]

        public virtual Horse GuidHorse { get; set; }
    }