// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

    public class CompetitionLevel
    {
        [Key]
        public int LevelId { get; set; }

        [Required]
        public string Name { get; set; }

        public int MinHorseAge { get; set; }

        public int MinPointRequirement { get; set; }

        [Required]
        public PointType PointType { get; set; }

        public int EntryFee { get; set; }


        public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();

        public virtual ICollection<CompetitionType> AllowedTypes { get; set; } = new List<CompetitionType>();
    }