// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

    public  class Competition
    {
        [Key]
        public int CompetitionId { get; set; }

        [Required]
        public string CompetitionName { get; set; }

        public DateTime Date { get; set; }

        public DateTime EntryOpenAt { get; set; }

        public DateTime EntryCloseAt { get; set; }

        public DateTime? ResultsAvailableAt { get; set; }

        public int DisciplineGroupId { get; set; }

        public int CompetitionLevelId { get; set; }

        public int CompetitionTypeId { get; set; }

        [Required]
        [Column(TypeName = "nvarchar(50)")]
        public Discipline DisciplineId { get; set; }

        [ForeignKey("DisciplineGroupId")]

        public virtual DisciplineGroup DisciplineGroup { get; set; }

    public int SeasonId { get; set; }  // FK

    public virtual Season Season { get; set; }  // Navigation
    public int VenueId { get; set; }

        [Column(TypeName = "nvarchar(50)")]
        public Weather ActualWeather { get; set; }


        public virtual ICollection<CompetitionEntry> CompetitionEntries { get; set; } = new List<CompetitionEntry>();

        [ForeignKey("CompetitionLevelId")]

        public virtual CompetitionLevel CompetitionLevel { get; set; }


        public virtual ICollection<CompetitionResult> CompetitionResults { get; set; } = new List<CompetitionResult>();

        [ForeignKey("CompetitionTypeId")]

        public virtual CompetitionType CompetitionType { get; set; }


        [ForeignKey("VenueId")]
 
        public virtual Venue Venue { get; set; }
    }