// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

    public class CompetitionType
    {
        [Key]
        public int TypeId { get; set; }

        [Required]
        public string Name { get; set; }

        public int RegistrationFee { get; set; }

        public PointType RequiredPointType { get; set; }

        public int RecoveryRequired { get; set; }

        public int? RequiredPoints { get; set; }

        public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();

        public virtual ICollection<CompetitionLevel> AllowedLevels{ get; set; } = new List<CompetitionLevel>();
    }