// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Competitions;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class DisciplineGroup
{
    [Key]
    public int DisciplineGroupId { get; set; }

    [Required]
    public string DisplayName { get; set; }

    [Required]
    public string AllowedGroundTypes { get; set; }

    public bool IsIndoorDiscipline { get; set; }


    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();

    [Required]
    public virtual ICollection<DisciplineGroupAllowedDiscipline> AllowedDisciplines { get; set; } = new List<DisciplineGroupAllowedDiscipline>();
}