// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class Venue
{
    [Key]
    public int VenueId { get; set; }

    [Required]
    public string VenueName { get; set; }

    public int ArenaType { get; set; }

    public int GroundType { get; set; }

    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();
}