// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Domain.Models.Horses.Breeds;
using Domain.Models.Horses.HorseStats;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class Breed
{
    [Key]
    public int BreedId { get; set; }

    [Required]
    public string BreedName { get; set; }

    public string RegistryInitials { get; set; }

    public int MinHeight { get; set; }

    public int MaxHeight { get; set; }

    public double DisciplinAffinity { get; set; }

    public bool IsFoundationBred { get; set; }

    public RarityTier Rarity { get; set; }

    public int MaxFoalings => BreedConfig.MaxFoalingsByRarity[Rarity];

    public int Acquisition { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? LaunchSalePrice { get; set; }

    public int? LaunchQuantity { get; set; }

    public bool CanMix { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime DateModified { get; set; }

    public int? BreedGroupId { get; set; }

    public int? SaleEventTypeId { get; set; }

    [ForeignKey("BreedGroupId")]

    public virtual BreedGroup BreedGroup { get; set; }

    public PerformanceAttributes MinPerformance { get; set; }

    public PerformanceAttributes MaxPerformance { get; set; }

    public PerformanceWeight PerformanceWeight { get; set; }

    public ConformationAttributes MaxConformation { get; set; }

    public ConformationAttributes MinConformation { get; set; }

    public ConformationWeight ConformationWeight { get; set; }


    public TemperamentInformation TemperamentInformation { get; set; }


    public virtual ICollection<FoundationPair> FoundationPairParentBreedDams { get; set; } = new List<FoundationPair>();


    public virtual ICollection<FoundationPair> FoundationPairParentBreedSires { get; set; } = new List<FoundationPair>();


    public virtual ICollection<FoundationPair> FoundationPairResultBreeds { get; set; } = new List<FoundationPair>();


    public virtual ICollection<HorseTypeSubmission> HorseTypeSubmissions { get; set; } = new List<HorseTypeSubmission>();


    public virtual ICollection<HorseType> HorseTypes { get; set; } = new List<HorseType>();

    [ForeignKey("SaleEventTypeId")]

    public virtual SaleEventType SaleEventType { get; set; }

public virtual ICollection<BreedCrossGroup> BreedCrossGroups { get; set; }
}