// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Horses.Breeds;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class CrossGroup
{
    [Key]
    public int CrossGroupId { get; set; }

    [Required]
    public string Name { get; set; }

    public int? BreedGroupId { get; set; }

    [ForeignKey("BreedGroupId")]

    public virtual BreedGroup BreedGroup { get; set; }

    public ICollection<BreedCrossGroup> BreedCrossGroups { get; set; } = new List<BreedCrossGroup>();
}
