// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class FoundationPair
{
    [Key]
    public int Id { get; set; }

    public int ParentBreedDamId { get; set; }

    public int ParentBreedSireId { get; set; }

    public int ResultBreedId { get; set; }

    public bool IsOrderSensitive { get; set; }

    [ForeignKey("ParentBreedDamId")]

    public virtual Breed ParentBreedDam { get; set; }

    [ForeignKey("ParentBreedSireId")]

    public virtual Breed ParentBreedSire { get; set; }

    [ForeignKey("ResultBreedId")]

    public virtual Breed ResultBreed { get; set; }
}