// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Horses.HorseStats;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public class ConfPerfTempAttributes
{
    [Key]
    public int CPTId { get; set; }

    public ConformationAttributes ConformationAttributes { get; set; }

    public PerformanceAttributes PerformanceAttributes { get; set; }

    public TemperamentInformation TemperamentInformation { get; set; }

    public Guid GuidHorseId { get; set; }

    [ForeignKey("GuidHorseId")]

    public virtual Horse Horse { get; set; }
}