// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class HorsePurposeStat
{
    [Key]
    public int PurposeId { get; set; }

    [Required]
    public string PurposeName { get; set; }

    public PurposeType PurposeType { get; set; }

    public double BaseStatInheritanceMultiplier { get; set; }

    public double TrainingPointInheritanceMultiplier { get; set; }

    public int MaxFoals { get; set; }
}