// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class TemperamentInformation
{
    [Key]
    public int TemperamentId { get; set; }

    [Required]
   public  Temperament Temperament { get; set; }

    [Required]
    public string AffectedBy { get; set; }

    [Required]
    public string EffectOnPerformance { get; set; }

    [Required]
    public string PerformsWellIn { get; set; }

    [Required]
    public string PerformsPoorlyIn { get; set; }

    [Required]
    public string PreferredGroundTypes { get; set; }
}