// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Sales;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


    public class AuctionBid
    {
        [Key]
        public int AuctionBidId { get; set; }

    public int AuctionSaleId { get; set; }

    [ForeignKey(nameof(AuctionSaleId))]
    public virtual AuctionSale AuctionSale { get; set; }

    [Required]
        public Guid BidderEquineEstateId { get; set; }

        [Required]
        public int BidAmount { get; set; }

        [Required]
        public DateTime TimeBidPlaced { get; set; }

        [ForeignKey("BidderEquineEstateId")]
        public virtual EquineEstate BiddersEquineEstate{ get; set; }
    }