// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class SaleEventType
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int Season { get; set; }

    public bool IsInviteOnly { get; set; }

    public bool RequiresApproval { get; set; }

    [Required]
    public string ConditionIdentifiers { get; set; }


    public virtual ICollection<Breed> Breeds { get; set; } = new List<Breed>();
}