// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class Vendor
{
    [Key]
    public int VendorId { get; set; }

    [Required]
    public string Name { get; set; }

    public int Type { get; set; }
}