// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class EquineEstatesOwner
{
    [Key]
    public int Id { get; set; }

    public Guid EquineEstateId { get; set; }

    public Guid UserId { get; set; }

    public bool IsPrimaryOwner { get; set; }

    [ForeignKey("EquineEstateId")]
    public virtual EquineEstate EquineEstate { get; set; }

    [ForeignKey("UserId")]
    public virtual User User { get; set; }
}