// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Users;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class EquineEstate
{
    [Key]
    public Guid EquineEstateId { get; set; }

    public string EstateName { get; set; }

    public int HorseAmount { get; set; }

    public int CurrentBalance { get; set; }

    [Required]
    public string ProfileEdit { get; set; }

    public bool IsSystemEstate { get; set; }


    public virtual ICollection<EquineEstatesOwner> EquineEstatesOwners { get; set; } = new List<EquineEstatesOwner>();


    public virtual ICollection<Facility> Facilities { get; set; } = new List<Facility>();

}