// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Index("EquineEstateId", Name = "IX_Facilities_EquineEstateId")]
public abstract class Facility
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Location { get; set; }

    public int HorseCapacity { get; set; }

    public int PersonnelCapacity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Cost { get; set; }

    public Guid? EquineEstateId { get; set; }

    [Required]
    [StringLength(13)]
    public string FacilityType { get; set; }


    [ForeignKey("EquineEstateId")]
    public virtual EquineEstate EquineEstate { get; set; }
}

public class Personnel : Facility
{
    public Personnel()
    {
        FacilityType = nameof(Personnel);
    }

    public int StaffCount { get; set; }
    public string Role { get; set; } // e.g., Groom, Trainer
}

public class Arena : Facility
{
    public Arena()
    {
        FacilityType = nameof(Arena);
    }

    public GroundType SurfaceType { get; set; } // e.g., Sand, Grass
    public bool IsIndoor { get; set; }
}

public class Pasture : Facility
{
    public Pasture()
    {
        FacilityType = nameof(Pasture);
    }
    public int Acreage { get; set; }
    public bool HasShelter { get; set; }
}