// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class Foaling
{
    [Key]
    public int FoalingId { get; set; }

    public Guid EquineEstateId { get; set; }

    public DateOnly CoveringDate { get; set; }

    public DateOnly FoalingDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal EstimatedValueIncrease { get; set; }

    [ForeignKey("EquineEstateId")]
    public virtual EquineEstate EquineEstate { get; set; }

    // Link to foal
    public Guid FoalId { get; set; }
    public Horse Foal { get; set; }

    // Link to parents (redundant but useful for querying events by parent)
    public Guid DamId { get; set; }
    public Horse Dam { get; set; }

    public Guid SireId { get; set; }
    public Horse Sire { get; set; }

}