// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class Foaling
{
    [Key]
    public int FoalingId { get; set; }

    public Guid EquineEstateId { get; set; }

    public Guid DamId { get; set; }

    public Guid SireId { get; set; }

    public Guid FoalId { get; set; }

    public DateTime FoalingDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal EstimatedValueIncrease { get; set; }

    [ForeignKey("DamId")]
    public virtual Horse Dam { get; set; }

    [ForeignKey("EquineEstateId")]
    public virtual EquineEstate EquineEstate { get; set; }

    [ForeignKey("FoalId")]
    public virtual Horse Foal { get; set; }

    [ForeignKey("SireId")]
    public virtual Horse Sire { get; set; }
}