// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Domain.Models.Horses;
using Domain.Models.Horses.Relations;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class Horse
{
    [Key]
    public Guid GuidHorseId { get; set; }

    [Required]
    public string HorseRegistryId { get; set; }

    public bool IsActive { get; set; }


    [Required]
    public string HorseName { get; set; }

    public int Age { get; set; }

    public int Sex { get; set; }

    public DateOnly BirthDate { get; set; }

    public DateOnly AgingDate { get; set; }

    public int Temperament { get; set; }

    public int HorseTypeId { get; set; }

    public int HorsePurposeType { get; set; }

    public double Value { get; set; }

    public virtual DisciplineGroup DisciplineGroup { get; set; }

    [Required]
    public string DisciplineGroupId { get; set; }

    public bool IsInPasture { get; set; }

    public bool IsFoal { get; set; }

    public bool IsVaulted { get; set; }

    public bool IsShared { get; set; }

    public int? LegacyHorseId { get; set; }

    public ICollection<CompetitionProgression> CompetitionProgressions { get; set; }


    public virtual ICollection<CompetitionResult> CompetitionResults { get; set; } = new List<CompetitionResult>();

    public virtual ICollection<Foaling> FoalingDams { get; set; } = new List<Foaling>();

    public virtual Foaling Foaling { get; set; }

    public virtual ICollection<Foaling> FoalingSires { get; set; } = new List<Foaling>();

    public CompetitionProgression Progression { get; set; }
    public virtual ConfPerfTempAttributes ConfPerfTempAttributes { get; set; }

    [ForeignKey("HorseTypeId")]
    public virtual HorseType HorseType { get; set; }

    public HorseArcheType Archetype { get; set; }

    public virtual ScorePotential ScorePotential { get; set; }

    public virtual ICollection<TrophyBase> TrophyBases { get; set; } = new List<TrophyBase>();

    public virtual BreedQualityScore BreedQualityScore { get; set; }

    public double? CachedBQS { get; private set; }

    public virtual PerformanceQualityScore PerformanceQualityScore { get; set; }

    public double ChachedPQS { get; private set; }

    public virtual ICollection<HorseOwnership> HorseOwnerList { get; set; } = new List<HorseOwnership>();

    public virtual ICollection<HorseBoarding> HorseBoardings { get; set; } = new List<HorseBoarding>();

}