// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public class BreedQualityScore
{
    public int Id { get; set; }

    public double Score { get; set; }

    public DateTime LastEvaluatedAt { get; set; }

    public string EvaluationNotes { get; set; }

    public Guid HorseId { get; set; }
    public Horse Horse { get; set; }
}