// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class PerformanceQualityScore
{
    [Key]
    public int Id { get; set; }

    public Guid HorseId { get; set; }

    public double Score { get; set; }

    public int TotalCompetitions { get; set; }

    public int Wins { get; set; }

    public double AveragePlacement { get; set; }

    public DateTime LastUpdated { get; set; }

    [ForeignKey("HorseId")]

    public virtual Horse Horse { get; set; }
}