// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public  class ScorePotential
{
    [Key]
    public Guid HorseId { get; set; }

    public double CPSMin { get; set; }

    public double CPSMax { get; set; }

    public double BQSMin { get; set; }

    public double BQSMax { get; set; }

    [ForeignKey("HorseId")]
    public virtual Horse Horse { get; set; }
}