// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Domain.Models.Enums;

namespace Domain.Models;


public class HorseTypeSubmission
{
    [Key, Required]
    public int HorseTypeSubmissionID { get; private set; }

    [Required]
    public Guid SubmittedByUserId { get; set; } // Reference to user who submitted

    public virtual User SubmittedByUser { get; set; }

    public int MaturityStage { get; set; }


    [ForeignKey("Breed"), Required]
    public int BreedID { get; set; }

    public Breed Breed { get; private set; }

    [Required]
    public TypeCategory SubmissionType { get; private set; }

    [Required]
    public bool IsAdult { get; private set; }

    public SubmissionStatus Status { get; set; } = SubmissionStatus.Pending;

    public SeasonalOccasion Occasion { get; private set; } = SeasonalOccasion.None;


    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;

    [Required]
    public bool IsHorse { get; private set; } // Not sure what else this would be?

    [Required]
    public string PictureRef { get; set; }

    public virtual ICollection<HorseTypeSubmissionArtist> HorseTypeSubmissionArtists { get; set; } = new List<HorseTypeSubmissionArtist>();
}