// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class HorseArtistsApproval
{
    [Key]
    public int SubmissionId { get; set; }

    public Guid GuidUserId { get; set; }

    public Guid UserId { get; set; }

    [Required]
    public string PortfolioLink { get; set; }

    [Required]
    public string AdditionalInfo { get; set; }

    public SubmissionStatus Status { get; set; } = SubmissionStatus.Pending;

    public int MaturityStage { get; set; }

    public DateTime SubmittedAt { get; set; }

 
}