// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public  class HorseType
{
    [Key]
    public int HorseTypeId { get; set; }

    public int HorseTypeSubmissionId { get; set; }

    public int BreedId { get; set; }

    public int TypeCategory { get; set; }

    public HorseGender HorseGender { get; set; } 

    public int TypeHorsesAlive { get; set; }

    public int MaturityStage { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("BreedId")]

    public virtual Breed Breed { get; set; }

    [ForeignKey("HorseTypeSubmissionId")]

    public virtual HorseTypeSubmission HorseTypeSubmission { get; set; }

    public virtual ICollection<HorseArtist> Artists { get; set; }


    public virtual ICollection<Horse> Horses { get; set; } = new List<Horse>();
}