// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;


public class HorseTypeSubmissionArtist
{
    [Key]
    public int Id { get; set; }

    public int HorseTypeSubmissionId { get; set; }

    public int HorseArtistId { get; set; }

    public bool IsApproved { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public virtual HorseTypeSubmission HorseTypeSubmission { get; set; }
    public virtual HorseArtist HorseArtist { get; set; }

}